# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       libpciaccess
Summary:    PCI access library
Version:    0.12.1
Release:    0
Group:      System/Libraries
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/archive/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libpciaccess.yaml
Patch0:     libpciaccess-no-root.patch
Requires:   hwdata
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig


%description
Generic PCI access library


%package devel
Summary:    PCI access library development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Generic PCI access library development package


%prep
%setup -q -n %{name}-%{version}

# libpciaccess-no-root.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc COPYING AUTHORS ChangeLog
%{_libdir}/libpciaccess.so.0
%{_libdir}/libpciaccess.so.0.10.8
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/pciaccess.h
%{_libdir}/libpciaccess.so
%{_libdir}/pkgconfig/pciaccess.pc
# << files devel

