# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
Name:       libpciaccess
Summary:    PCI access library
Version:    0.16
Release:    1
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/archive/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libpciaccess.yaml
Patch0:     libpciaccess-no-root.patch
Requires:   hwdata
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description
Generic PCI access library

%package devel
Summary:    PCI access library development package
Requires:   %{name} = %{version}-%{release}

%description devel
Generic PCI access library development package

%prep
%setup -q -n %{name}-%{version}

# libpciaccess-no-root.patch
%patch0 -p1

%build

%configure --disable-static
make %{?jobs:-j%jobs}

%install
rm -rf %{buildroot}
%make_install

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc COPYING AUTHORS ChangeLog
%{_libdir}/libpciaccess.so.0*

%files devel
%defattr(-,root,root,-)
%{_includedir}/pciaccess.h
%{_libdir}/libpciaccess.so
%{_libdir}/pkgconfig/pciaccess.pc

